GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
USE cloud_portal;
#UPDATE configuration SET value='' WHERE name='';
UPDATE configuration SET value='http://cwiki.apache.org/CLOUDSTACK/' WHERE name='customer.home.url';
UPDATE configuration SET value='http://www.citrix.co.jp/products/srp/cloudportal_businessmanager.html' WHERE name='customer.cloudmktg.url';
UPDATE configuration SET value='cpbm.cloud.local' WHERE name='vmops.public.host';
UPDATE configuration SET value='takashi@sugano.local' WHERE name='admin.support.email';
UPDATE configuration SET value='noreply@sugano.local' WHERE name='vmops.internal.email';
UPDATE configuration SET value='true' WHERE name='vmops.error.notification.enable';
UPDATE configuration SET value='error@cpbm.cloud.local' WHERE name='vmops.error.notification.from';
UPDATE configuration SET value='takashi@sugano.local' WHERE name='vmops.error.notification.to';
UPDATE configuration SET value='cpbm' WHERE name='vmops.error.notification.prefix';
UPDATE configuration SET value='JST' WHERE name='vmops.portal.default.user.timezone';
UPDATE configuration SET value='accounts-request@sugano.local' WHERE name='vmops.approvalRequest.email';
UPDATE configuration SET value='billing-update@sugano.local' WHERE name='vmops.billingUpdate.email';
UPDATE configuration SET value='sales@cpbm.cloud.local' WHERE name='vmops.sales.email';
UPDATE configuration SET value='sales@sugano.local' WHERE name='vmops.sales.support.email';
UPDATE configuration SET value='finance@sugano.local' WHERE name='vmops.finance.email';
UPDATE configuration SET value='support@cpbm.cloud.local' WHERE name='vmops.support.email';
UPDATE configuration SET value='support@sugano.local' WHERE name='vmops.helpdesk.email';
UPDATE configuration SET value='JPY' WHERE name='default.currency';
#UPDATE configuration SET value='' WHERE name='';
