GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
USE cloud;
#UPDATE configuration SET value='' WHERE name='';
UPDATE user SET password=RAND() WHERE id=1;
UPDATE configuration SET value='60' WHERE name='account.cleanup.interval';
UPDATE configuration SET value='takashi@sugano.com' WHERE name='alert.email.addresses';
UPDATE configuration SET value='alert@csms.cloud.local' WHERE name='alert.email.sender';
UPDATE configuration SET value='smtp.sugano.com' WHERE name='alert.smtp.host';
UPDATE configuration SET value='25' WHERE name='alert.smtp.port';
UPDATE configuration SET value='0.99' WHERE name='cluster.cpu.allocated.capacity.disablethreshold';
UPDATE configuration SET value='0.99' WHERE name='cluster.memory.allocated.capacity.disablethreshold';
UPDATE configuration SET value='2' WHERE name='cpu.overprovisioning.factor';
UPDATE configuration SET value='true' WHERE name='enable.ec2.api';
UPDATE configuration SET value='true' WHERE name='enable.s3.api';
UPDATE configuration SET value='600' WHERE name='expunge.delay';
UPDATE configuration SET value='600' WHERE name='expunge.interval';
UPDATE configuration SET value='cloud.local' WHERE name='guest.domain.suffix';
UPDATE configuration SET value='8096' WHERE name='integration.api.port';
UPDATE configuration SET value='60' WHERE name='network.gc.interval';
UPDATE configuration SET value='60' WHERE name='network.gc.wait';
UPDATE configuration SET value='172.16.0.0/16' WHERE name='secstorage.allowed.internal.sites';
UPDATE configuration SET value='60' WHERE name='storage.cleanup.interval';
#UPDATE configuration SET value='' WHERE name='';
UPDATE service_offering SET ram_size = 128 WHERE vm_type = 'consoleproxy';
UPDATE service_offering SET ram_size = 128 WHERE vm_type = 'secondarystoragevm';
