#!/bin/bash
#
# chkconfig: 35 99
# description: do post-installation setup

### BEGIN INIT INFO
# Provides: postslave
# Default-Start:  345
# Short-Description: do post-installation setup
# Description: do post-installation setup for XS slave
### END INIT INFO

#
# Variables
#
_DEBUG='logger -p user.info -t postinstall -- '
_host=$(hostname)

$_DEBUG starting $0 $*

#
# Configure IP address for storage network
#
if [ -z "$(xe pif-list device=eth4 params=IP --minimal)" ]; then
  xe pif-reconfigure-ip mode=static IP=172.24.0.$(grep IPADDR /etc/sysconfig/network-scripts/ifcfg-xenbr0 | cut -d. -f4) netmask=255.255.128.0 uuid=$(xe pif-list device=eth4 --minimal)
#  xe pif-param-set disallow-unplug=true uuid=$_pif3
#  xe pif-param-set other-config:ManagementPurpose="Storage" uuid=$_pif3
fi

#
# Apply hotfixes
#
_TMP=/tmp

if [ ! -e $_TMP/patches_downloaded ]; then
  $_DEBUG downloading patches
  wget -q -nd -P $_TMP ftp://172.16.1.1/XS$(xe host-list name-label=`uname -n` params=software-version --minimal | cut -d\; -f3 | tr -d [:alpha:][:blank:][:punct:])E/*.xsupdate
  touch $_TMP/patches_downloaded
fi

touch $_TMP/patches_applying

_hostuuid=$(xe host-list name-label=$_host --minimal)
for xsupdate in $_TMP/*.xsupdate; do
  $_DEBUG uploading ${xsupdate##*/}
  _patchuuid=$(xe patch-upload file-name=$xsupdate)
  mv $xsupdate ${xsupdate}d
  if [ -z "$_patchuuid" ]; then
    $_DEBUG skipping ${xsupdate##*/}
    continue;
  fi
  $_DEBUG processing "$(xe patch-list uuid=$_patchuuid params=name-label --minimal), $(xe patch-list uuid=$_patchuuid params=name-description --minimal)"
  $_DEBUG xe patch-apply host-uuid=$_hostuuid uuid=$_patchuuid
  xe patch-apply host-uuid=$_hostuuid uuid=$_patchuuid
  xe patch-list uuid=$_patchuuid >> $_TMP/patches_applying
  _patchaction=$(xe patch-list uuid=$_patchuuid params=after-apply-guidance --minimal)
  $_DEBUG doing $_patchaction
  if [ "$_patchaction" == "restartXAPI" ]; then
    xe-toolstack-restart
    sleep 60
  elif [ "$_patchaction" == "restartHost" ]; then
    reboot
    exit
  fi
done

mv $_TMP/patches_applying $_TMP/patches_applied
$_DEBUG all patches have been applied

rm -f /etc/rc3.d/S99zzpostslave

exit 0
